<a href="https://colab.research.google.com/github/sriharshitha12/Python-For-Datascience-1261/blob/main/lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
student_marks = np.random.randint(0, 101, size=(10, 3))
print(student_marks)



[[14 80 15]
 [15 52  5]
 [71 73 58]
 [39 32 88]
 [77 79 44]
 [77 13  1]
 [45  6 16]
 [ 1  3 94]
 [73 78 37]
 [36  5 55]]


In [6]:
overall_average = np.mean(student_marks)
overall_minimum = np.min(student_marks)
overall_maximum = np.max(student_marks)
print(f"Overall Average Mark: {overall_average:.2f}")
print(f"Overall Minimum Mark: {overall_minimum}")
print(f"Overall Maximum Mark: {overall_maximum}")


Overall Average Mark: 55.07
Overall Minimum Mark: 7
Overall Maximum Mark: 93


In [8]:
first_three=student_marks[:3, :]
print("Marks of the first three students:")
print(first_three)
student_at_index_5_marks = student_marks[5, :]
print("\nMarks of the student at index 5:")
print(student_at_index_5_marks)

Marks of the first three students:
[[29 91 48]
 [67 84 39]
 [93 53 88]]

Marks of the student at index 5:
[43 10 89]


In [11]:
high_scoring_students = student_marks[np.any(student_marks > 80, axis=1)]

print("\nStudents scoring above 80 in at least one subject:")
print(high_scoring_students)


Students scoring above 80 in at least one subject:
[[29 91 48]
 [67 84 39]
 [93 53 88]
 [54 92 78]
 [43 10 89]
 [46 92 92]]


In [12]:
subject_wise_marks = student_marks.T

print("\nSubject-wise Marks Array (transposed):")
print(subject_wise_marks)
subject_average_marks = np.mean(subject_wise_marks, axis=1)
subject_minimum_marks = np.min(subject_wise_marks, axis=1)
subject_maximum_marks = np.max(subject_wise_marks, axis=1)

print("\nSubject-wise Average Marks:")
print(subject_average_marks)

print("\nSubject-wise Minimum Marks:")
print(subject_minimum_marks)

print("\nSubject-wise Maximum Marks:")
print(subject_maximum_marks)


Subject-wise Marks Array (transposed):
[[29 67 93 65 54 43 69 46 11 49]
 [91 84 53  8 92 10  7 92 26 71]
 [48 39 88 23 78 89 33 92 71 31]]

Subject-wise Average Marks:
[52.6 53.4 59.2]

Subject-wise Minimum Marks:
[11  7 23]

Subject-wise Maximum Marks:
[93 92 92]
